spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: chat-service
              uri: http://localhost:3001
              predicates:
                - Path=/chats/**

            - id: chat-websocket
              uri: ws://localhost:3001
              predicates:
                - Path=/chat/**

            - id: main-service
              uri: http://localhost:8081
              predicates:
                - Path=/**

server.port: 8080

cors.allowed.origins: ${CORS_ALLOWED_ORIGINS}

access.token.value: ${ACCESS_TOKEN_SECRET}