[gdrive]
type = drive
scope = drive
# You must generate these credentials or use rclone config to create this file
# See instructions in README or scripts/backup-service/README.md
token = {"access_token":"PLACEHOLDER","token_type":"Bearer","refresh_token":"PLACEHOLDER","expiry":"2026-08-15T00:00:00Z"}
team_drive = 
